import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import TopAppBar from "@/components/new-home/Topappbar";
import BottomNavBar from "@/components/new-home/BottomNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-surface text-on-surface font-body selection:bg-secondary-container selection:text-on-secondary-container`}
      >
        <TopAppBar />
        {children}
        <BottomNavBar />
      </body>
    </html>
  );
}
